### ISSUE TITLE
app-definition.json is missing from jee-sample

### ISSUE THREAD

**Issue by arun-gupta** [dcos-labs/dcos-maven-plugin#10]
`app-definition.json` is missing from https://github.com/dcos-labs/dcos-maven-plugin/tree/master/samples/jee-sample.

Purpose of `spring-boot-maven-plugin` in `jee-sample` is not clear either.

**Comment by unterstein** [comment]
oh snap, thanks for reporting!
Spring boot maven plugin must be copy/past error. Also added the example app definition.
